### ISSUE TITLE
编译APP vue 报错

### ISSUE THREAD

**Issue by guiyinrenshi** [houlangs/Newlangs4#39]
[vite:vue] Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
error during build:
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
    at resolveCompiler (D:\Desktop\Newlangs4-4.5.6\Newlangs4-4.5.6\app-newlangs-vue\node_modules\@vitejs\plugin-vue\dist\index.cjs:16:11)
    at Object.buildStart (D:\Desktop\Newlangs4-4.5.6\Newlangs4-4.5.6\app-newlangs-vue\node_modules\@vitejs\plugin-vue\dist\index.cjs:2671:46)
    at file:///D:/Desktop/Newlangs4-4.5.6/Newlangs4-4.5.6/app-newlangs-vue/node_modules/rollup/dist/es/shared/node-entry.js:25336:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 5)
    at async PluginDriver.hookParallel (file:///D:/Desktop/Newlangs4-4.5.6/Newlangs4-4.5.6/app-newlangs-vue/node_modules/rollup/dist/es/shared/node-entry.js:25264:9)
    at async file:///D:/Desktop/Newlangs4-4.5.6/Newlangs4-4.5.6/app-newlangs-vue/node_modules/rollup/dist/es/shared/node-entry.js:26488:13
    at async catchUnfinishedHookActions (file:///D:/Desktop/Newlangs4-4.5.6/Newlangs4-4.5.6/app-newlangs-vue/node_modules/rollup/dist/es/shared/node-entry.js:25702:16)
    at async rollupInternal (file:///D:/Desktop/Newlangs4-4.5.6/Newlangs4-4.5.6/app-newlangs-vue/node_modules/rollup/dist/es/shared/node-entry.js:26485:5)
    at async build (file:///D:/Desktop/Newlangs4-4.5.6/Newlangs4-4.5.6/app-newlangs-vue/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:47951:18)

**Comment by guiyinrenshi** [comment]
已解决

**Comment by myitcloud** [comment]
老板 能不能帮忙搭建下哇，我一直失败

**Comment by SunWuyuan** [comment]
有问题可以开新的issues提问，除非你认为你遇到了与这个问题相同的错误
